### ISSUE TITLE
Change JIRA ticket layout

### ISSUE THREAD

**Issue by jerbia** [aquasecurity/alm-integration#4]
We should the JIRA ticket to include the following information (html format):
- Image name: <image name> 
- Registry: <registry name> 
- Image is compliance / Image is non-compliant (based on “disallowed” flag) 
- Vulnerability summary: a graphical view of high/medium/low issues 
A picture containing drawing
- Malware found: yes/no (show this only if scan_malware flag is “yes”) 
- Sensitive data found: yes/no (show this only if scan_sensitive_data flag is “yes”) 
- Assurance controls: show list of assurance controls. Near every one show whether it passed or failed. 

*<in case this is a rescan that found new vulnerabilities>*
Discovered vulnerabilities from last scan: 
<Display the details of vulnerabilities based on their category> 
<Each vulnerability should include the vulnerable package name, version, fix version and CVE>
<Do not display a category that is empty>  
 
Previously discovered vulnerabilities: 
<Each vulnerability should include the vulnerable package name, version, fix version and CVE>

*<in case this is a first scan>*
Found vulnerabilities:
<display the details of the vulnerabilities based on their category>
<Each vulnerability should include the vulnerable package name, version, fix version and CVE>

**Comment by afdesk** [comment]
@jerbia I don't find vulnerabilities from last scan.
Should I create a new request to API)? I can use `previous_digest` for this one.
Or just I selected wrong images...

**Comment by jerbia** [comment]
You need to save it in the bolt DB...

________________________________

**Comment by afdesk** [comment]
> You need to save it in the bolt DB...

What about first result.
Is it empty for first webhook?

**Comment by afdesk** [comment]
@jerbia I wanted to use a digest field as DB key. But now I think that's wrong. 
is there a field which could use as key?

**Comment by jerbia** [comment]
You can use the "digest"-"image"-"registry" (the combination of the three fields) for the unique ID.

**Comment by jerbia** [comment]
@afdesk what I suggest is:
1.  When the webhook is triggered, take the digest-image-registry and check if it exists in the boltdb.
2. If not exist, open a JIRA ticket. Save to DB all the reported vulnerabilities for the image.
3. If exists - read from the DB the last scan results. It should include the number of critical/high/medium/low/negliggable vulnerabilities and malware. Compare it to the current scan results. If it is the same, do nothing. If different - create a new JIRA ticket, showing the new vulnerabilities and the old ones.

**Comment by afdesk** [comment]
> You can use the "digest"-"image"-"registry" (the combination of the three fields) for the unique ID.
ok, I thought that `digest` isn't unique param and there are different digests for the same vulnerabilities lists. I was wrong.

**Comment by jerbia** [comment]
Digest is unique.
It might be that same image is stored on two registries, in that case you will get same digest twice for different images. Due to that I suggest you add the image and registry name to the uniqueness of the object.

**Comment by afdesk** [comment]
@jerbia for test I see image `alpine:3.8` (registry `Docker Hub`) and see that `digest` is equal `previous_digest`.
Is it normal?

**Comment by jerbia** [comment]
Yes. Previous Digest is the digest of the image on the previous scan. If equal it means image did not change in the registry. 
If not equal - it means this is a new image that was pushed to the registry that overrides the previous one.

Since you are only caching the digest you will know that a replacement for an image with same name happened. This is OK.

**Comment by afdesk** [comment]
@jerbia I see a new template of config file (cfg.yalm). 

There are a few moments:
1. Can we use a `projectKey` instead of `project id`? I think that `Project id` is Jira's inner data.

2. What is mean a `project name`? Now it uses as project key. There is an error if `project name` doesn't match `project id`

3. `IsuueType` is empty, but issue type is required. It should set up, or need default value. `Bug`?

4. Now `priority` and `assignee` are required params. Is it correct? Maybe I need default values?
`High` and current user?

5. Actions with `description` param. What I have to do with it? this param overlays rendered data. is it correct?

**Comment by jerbia** [comment]
Few fixes:
- Change to "Image is complaint" (and not "Image is compliance"). Move it to a new line
- Malware found: No (instead of "no")
- Sensitive data found: No (instead of "no")
- Move the malware and sensitive data before the table

Remove the "Found Vulnerabilities" if there are 0 vulnerabilities...

![image](https://user-images.githubusercontent.com/3126261/81950786-120ffb80-960d-11ea-95fa-1cc5844b2645.png)

**Comment by afdesk** [comment]
@jerbia Can you tell me how to build previous (or next) scan for tests?

**Comment by jerbia** [comment]
@afdesk I don't have a way to create an image scan that will show difference in vulnerabilities. You will need to simulate this in the unit tests.
