### ISSUE TITLE
Add malware and sensitive data file names to the message details

### ISSUE THREAD

**Issue by jerbia** [aquasecurity/alm-integration#40]
Currently we specify whether malware/sensitive data was found (yes/no).
We should also include information about the actual files that are effected.

**Comment by vAndrucha77** [comment]
@jerbia is this something we are currently working on or is this an roadmap item?

**Comment by jerbia** [comment]
Yes, this is on our plans

**Comment by jerbia** [comment]
@afdesk can you add malware information? It's in the Webhook under (array of malware resources):
  "malware": [
    {
      "malware": "EICAR test file",
      "path": "/eicar.com",
      "hash": "sha1:3395856ce81f2b7382dee72602f798b642f14140"
    }
  ],
  
  You can scan jerbi/eicar:1 for malware.

**Comment by jerbia** [comment]
Sensitive data is under this JSON field (again - array):

"sensitive_data": [
    {
      "filename": "ssh_host_ecdsa_key",
      "path": "/etc/ssh/ssh_host_ecdsa_key",
      "type": "EC PRIVATE KEY",
      "hash": "sha1:46dead03015c298c2d454cc4fa2a702a99a96bca"
    },

**Comment by jerbia** [comment]
@vAndrucha77 this is now available.
