### ISSUE TITLE
Add a "Webhook" target

### ISSUE THREAD

**Issue by jerbia** [aquasecurity/alm-integration#44]
We would like to have a new type that is "webhook".
This type can be useful for users that want to send the scan results to a remote webhook.

The data sent should be identical in format to the data that alm-integration is getting (same payload). We should support all the policies also for the webhook type.

**Comment by afdesk** [comment]
@jerbia what about aggregate policies. Is it need to support too?

**Comment by jerbia** [comment]
yes, all policies should be supported

**Comment by afdesk** [comment]
@jerbia 
When I receive webhook from a server, I save only required data, the large part of received data is lost.
Should I save all "incoming data" for send to user's webhook?

**Comment by eurogig** [comment]
@jerbia 
I was just about the create this issue based on a request.  The webhook, should be able to be a pass through for the unchanged webhook JSON data. This ALM removes the webhook capability (and enhances it here) so there need to be an option for that to restore that capability in addition to applying policy.

**Comment by jerbia** [comment]
@afdesk yes - you should save all received data and send it to the next webhook pipe.
