### ISSUE TITLE
Add retention policy to delete old images from the database

### ISSUE THREAD

**Issue by jerbia** [aquasecurity/alm-integration#45]
Currently the BoltDB database size is not limited. We would like to have a new token in cfg.yaml that controls data retention:

Max_DB_Size=1000MB (if empty then unlimited)
Delete_Old_Data=180d (delete data older than 180 days). If empty then we do not delete.

These two settings should be under the main cfg.yaml section

**Comment by afdesk** [comment]
@jerbia it seems like this issue was solved.
