### ISSUE TITLE
Jira Plugin Logging

### ISSUE THREAD

**Issue by danielpj** [aquasecurity/alm-integration#51]
Does the Jira Plugin generate logs for troubleshooting? Authentication etc. Where might this be accessed? I am trying to track down why the plugin is not resolving the project names but unsure of where the issue lies. I know the cluster can reach the Jira server. Logs below:

2020/08/13 00:29:41 Starting WebServer....
2020/08/13 00:29:41 Starting AlertMgr....
2020/08/13 00:29:41 Loading alerts configuration file /policy/cfg.yaml/conf ....
2020/08/13 00:29:41 Listening for HTTPS on 0.0.0.0:8445
2020/08/13 00:29:41 Listening for HTTP on 0.0.0.0:8082
2020/08/13 00:29:41 no boards found with name XXXX board when getting all boards for User
2020/08/13 00:29:41 Starting Jira plugin "xxxx-jira"....
djohnson@jumphostpv16:~$ kubectl logs aqua-webhook-5ccdbc56b7-7lv29
2020/08/13 00:29:41 Starting WebServer....
2020/08/13 00:29:41 Starting AlertMgr....
2020/08/13 00:29:41 Loading alerts configuration file /policy/cfg.yaml/conf ....
2020/08/13 00:29:41 Listening for HTTPS on 0.0.0.0:8445
2020/08/13 00:29:41 Listening for HTTP on 0.0.0.0:8082
2020/08/13 00:29:41 no boards found with name XXXX board when getting all boards for User
2020/08/13 00:29:41 Starting Jira plugin "xxxx-jira"....

**Comment by jerbia** [comment]
@afdesk is it possible to add more logging before the "no boards found with name XXXX board when getting all boards for User" message? Something that will help identifying why no boards were found.

**Comment by jasonmcintosh** [comment]
We are hitting this exact same issue and it's causing the webhook to compeltely crash :(

**Comment by jasonmcintosh** [comment]
FYI: Found out our issues is that apparently the old webhook project is "dead".  Instead, I had to rebuild this docker image (or if you're a customer, you can pull it from the aquasec repo).  Once I changed htat, my Jira issues went away entirely.

**Comment by jerbia** [comment]
Closing issue as seem to be related with the old version of the alm-integration image.
