### ISSUE TITLE
Support Wildcards (*) for Image-Policy-Name value

### ISSUE THREAD

**Issue by ericgomes56** [aquasecurity/alm-integration#54]
Please extend support for wildcards (*) for Image-Policy-Name value

**Comment by jerbia** [comment]
@afdesk can you have the image names, in the Image-Policy-Name, supports wildcards?
For example:

Image-Policy-Name=[*:latest, mongo:1.*, mon*:*]

**Comment by afdesk** [comment]
@jerbia 
first and second options work now.
usage:
```
Policy-Image-Name: [":latest", "mongo:1"]
```

**Comment by krol3** [comment]
I did the following tests. It works using the name image without the tag. It will be nice if we could use regular expression.

--- Test01 ----
in the cfg.yaml: Policy-Image-Name: ["alpine:*"]

2020/11/26 13:18:46 Handling a scan result of 'Docker Hub/alpine:3.6'
2020/11/26 13:18:46 ScanService: Image "alpine:3.6" wasn't allowed (missed) by currentSettings for "kanban-jira".
2020/11/26 13:18:46 ScanService: Image "alpine:3.6" wasn't allowed (missed) by currentSettings for "scrum-jira".
-----Test02---- 
in the cfg.yaml: Policy-Image-Name: ["alpine"]
2020/11/26 13:23:43 Created new jira issue 10006

**Comment by jerbia** [comment]
@ericgomes56  this was now merged to master. You can use wildcards.
