### ISSUE TITLE
Send Scan Results Everytime

### ISSUE THREAD

**Issue by ericgomes56** [aquasecurity/alm-integration#58]
Please allow for the ability to toggle sending scan results always, regardless if the vulnerability count or severity has not changed.

Perhaps under 'Image-Policy-Name' in the cfg.yaml, we can add another flag to allow or disallow this feature.

**Comment by afdesk** [comment]
@jerbia 
I've made a new flag: `Policy-Show-All`.
if this flag is true, webhook app will handle old results. Default value is false.
I've created a pull request.

**Comment by jerbia** [comment]
Thanks @afdesk. Can you also update the readme.md with the new parameter?

**Comment by afdesk** [comment]
> readme.md
I've added it
