### ISSUE TITLE
Ticket creation policy

### ISSUE THREAD

**Issue by jerbia** [aquasecurity/alm-integration#6]
We would like to have an option that controls the criteria for opening a ticket. 
 
We would like to following fields to be configured via the cfg.yaml: 

Policy-Min-Vulnerability= high (what is the minimum vulnerability severity that triggers a ticket) 
Policy-Registry=<comma separated list of registries that will trigger opening a ticket) 
Policy-Image-Name=<comma separated list of images that will trigger opening a ticket)  
Policy-Non-Compliant=true/false (open ticket only if image is non-compliant)

**Comment by afdesk** [comment]
@jerbia are this policies for all plugins (jira, email) or only for Jira? 
if there are common rules, should i create new part in cfg.yaml?

**Comment by afdesk** [comment]
@jerbia I offer add ` settings` block to cfg.yalm. Is it ok?
```
- name: settings
  Policy-Min-Vulnerability: high # (what is the minimum vulnerability severity that triggers a ticket)
  Policy-Registry: [alpine, Docker image] #<comma separated list of registries that will trigger opening a ticket)
  Policy-Image-Name: [alpine,alpine2] #<comma separated list of images that will trigger opening a ticket)
  Policy-Non-Compliant: true # true/false (open ticket only if image is non-compliant)

- name: jira
  enable: true
  ...
```

**Comment by afdesk** [comment]
and this `settings` will be common for all plugins

**Comment by afdesk** [comment]
@jerbia 
I don't understand about a severity param.
Should I use aqua_severity, nvd_severity, vendor_severity or other?

**Comment by afdesk** [comment]
Now I use `aqua_severity`. Pushed.
