### ISSUE TITLE
Include SMTP server

### ISSUE THREAD

**Issue by cpt-redbeard** [aquasecurity/alm-integration#60]
The email notifications require user/pass/host/port for the SMTP configuration. Can the alm-integration include an SMTP server where you can define the user and domain the email is coming from?

example:
- name: my-email
  type: email 
  enable: true
  domain_sender: #Mandatory: The email address to use as a sender and domain for the SMTP server

**Comment by afdesk** [comment]
@cpt-redbeard Email integration parameters contain `sender` field, this is Sender's email address.
Can this parameter help you? Or should add a new logic?

**Comment by cpt-redbeard** [comment]
The request is to not require those parameters or the use of an external smtp. I believe this would require an internal smtp ?

**Comment by jerbia** [comment]
I need to better understand the use case - if you want to use an "internal" smtp server you can run an smtp server container (like this one https://hub.docker.com/r/namshi/smtp/) and configure the alm-integration to work against it.
I don't think we want the alm-integration to have a full-blown smtp server inside of it.

**Comment by jerbia** [comment]
Done. We added "UseMX" flag to the email settings.
