### ISSUE TITLE
Add field for application scope email to populate email recipient

### ISSUE THREAD

**Issue by cpt-redbeard** [aquasecurity/alm-integration#61]
The ricipient value should reference the email address from the application scope (sent to ALM). This would be an 'auto-get' for who the email notification should be directed to, from the audit data itself.

**Comment by jerbia** [comment]
Done.
You should specify "<%application_scope_owner%>" in the recipients field of cfg.yaml. For example:
recipients: ["<%application_scope_owner%>"]

This will send the email to the image application scope owners (as defined in the Application Scope assigned to the image)
