### ISSUE TITLE
error validating data: ValidationError(Deployment.spec.template.spec): unknown field "volumeMounts" in io.k8s.api.core.v1.PodSpec

### ISSUE THREAD

**Issue by ericgomes56** [aquasecurity/alm-integration#69]
Grabbed the latest branch for the alm-integration.

I encountered this error below when deploying the latest webhook.yaml in /aquasecurity/alm-integration/kubernetes.

![Screen Shot 2020-12-21 at 5 03 45 PM](https://user-images.githubusercontent.com/38416014/102826455-a6fe8280-43ae-11eb-9fad-04496b008ec7.png)

If I force with '--validate=false', the cfg.yaml isn't mounted into the webhook Deployment correctly:

![Screen Shot 2020-12-21 at 4 59 21 PM](https://user-images.githubusercontent.com/38416014/102826535-d7deb780-43ae-11eb-85f5-70c00e5885c6.png)

Here it is being referenced in line 73 of the webhook.yaml:

![Screen Shot 2020-12-21 at 5 07 14 PM](https://user-images.githubusercontent.com/38416014/102826636-13798180-43af-11eb-9454-340fc9f2c9cb.png)

**Comment by krol3** [comment]
This is a bug, I will submit the PR to fixed it

**Comment by krol3** [comment]
@ericgomes56 could you validate the fix>

**Comment by ericgomes56** [comment]
> @ericgomes56 could you validate the fix>

This works now, thanks.
