### ISSUE TITLE
Build an integration with Splunk

### ISSUE THREAD

**Issue by amirgabrieli** [aquasecurity/alm-integration#74]
We need ALM to send vulnerability scan results to Splunk. Can you please develop this model?
Thanks,

**Comment by afdesk** [comment]
Hello @amirgabrieli!
I'm working about this integration now.

I did work with Splunk, can you help me with some moments?
I want to send events to `HTTP Event Collector`. Is it OK?

also  which format is better for these events? 
I want to write a webhook title to an `event` field, and add other JSON to `nested`field.

**Comment by amirgabrieli** [comment]
hi,

I can provide you with a Splunk instance if you need one. 

Do you know how to Operator Splunk and create your own HTTP Event Listener?

Regarding the format - let me know what you recommend. I need a format where users will be able to see the image, the scan results, the registry, the vulnerabilities, the severity, the fixed version (if any), and vulnerability description, and the remediation actions if any.  I need customers to query by image, vulnerability, sevirity, has or doesn't have a fox. etc.
Can you suggest a format?

Thanks,

**Comment by afdesk** [comment]
@amirgabrieli 
Thanks for offer your instance. 
I think it will be useful for finish tests.
I'm using a docker instance now, and I'll try to use a trial period for cloud version.

Yes, I can create a HTTP Event Listener and send a JSON to my splunk instance. 

I need some time to think over about format. 
If i understand right, Splunk usually contains 'timestamp - event' data. 

Should ALM add one event for a scan result?
Maybe will it be a plain text like an event?

thanks!

**Comment by amirgabrieli** [comment]
you'll need a timestamp for each scan results, yes. I think one event per scan is the right approach. Json vs. plain-text, I don't know what's better, I mostly see people use json format.

**Comment by afdesk** [comment]
Hello @amirgabrieli 
I've pushed a first version of Splunk plugin for ALM integration to `issue-74` branch. 
would you mind using it?

If yes, I need to set next parameters in `cfg.yaml`:
```
- name: splunk
  type: splunk
  enable: true
  url: http://localhost:8088 # Mandatory. Url of a Splunk server
  token: <token> # Mandatory. a HTTP Event Collector Token
```

**Comment by amirgabrieli** [comment]
I'll test the Splunk plug-in and let you know how it works for us, thanks!
