### ISSUE TITLE
Aggregate Issues into one ticket

### ISSUE THREAD

**Issue by jerbia** [aquasecurity/alm-integration#8]
We would like to have the option to aggregate multiple image scans into a single ticket. 
If used, we will not create a ticket on every WebHook, but instead we will create the ticket once the aggregation is triggered (either we reached the number of images or the time). 
 
We would like to following fields to be configured via the cfg.yaml: 

Aggregate-Issues-Per-Ticket=<number> 
Aggregate-Timeout=<number of seconds to aggregate, maximum is 24 hours>

**Comment by afdesk** [comment]
@jerbia can you describe a format of timeout? just a number of seconds 1...86400?

**Comment by jerbia** [comment]
Aggregate-Timeout=Xs or Xm or Xh (basically 20s will be 20 seconds, 20m will be 20 minutes, etc.)
