### ISSUE TITLE
Ignore issues

### ISSUE THREAD

**Issue by jerbia** [aquasecurity/alm-integration#9]
Ability to ignore issues in specific images. 
 
We would like to following fields to be configured via the cfg.yaml: 

Ignore-Registry=<list of comma separated registries to ignore tickets> 
Ignore-Image-Name=<list of comma separated images to ignore, need to support wildcards >

**Comment by afdesk** [comment]
Which wildcards should it support? Only `*` and `?` ?

**Comment by afdesk** [comment]
@jerbia I offer to include these settings to issue 6. is it ok?

**Comment by jerbia** [comment]
Fixed.
